version: 2.1
workflows:
  default:
    jobs:
      - build-backend
      - build-frontend:
          requires: [build-backend]
      - release:
          requires: [build-frontend]

orbs:
  aws-eks: circleci/aws-eks@1.0.0
  kubernetes: circleci/kubernetes@0.11.1

jobs:
  build-backend:
    docker:
      - image: gebbissimo/ci_image:20221016-v3
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - backend-build
      # - run:
      #     name: build locally
      #     command: |
      #       cd backend
      #       make create-venv
      #       make install
      #       make lint

      #       make start-local-server
      #       sleep 5
      #       make curl-localhost
      #       make kill-local-server
      # - save_cache:
      #     key: backend-build
      #     paths:
      #       # TODO: is this the correct pip path?!
      #       - ~/.cache/pip
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: build docker
          command: |
            cd backend
            make build-docker

            ### We cannot test this easily because circleci uses remote docker...
            # make start-docker-server
            # sleep 3
            # make curl-localhost
            # make kill-docker-server

            make push-docker

      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: capstone-backend
          install-kubectl: true
      - run:
          name: deploy to kubeflow
          command: |
            kubectl version
            kubectl config view

            cd backend
            make create-kube-deployment
            sleep 10

            make forward-local-port-to-pod
            sleep 5
            make curl-localhost
            make kill-port-forwarding
      - attach_workspace:
          at: ~/
      - run:
          name: expose kubeflow deployment
          command: |
            cd backend
            make expose-deployment
            sleep 600

            make curl-service
            make store-backend-ip-address

  build-frontend:
    docker:
      - image: gebbissimo/ci_image:20221016-v1
    steps:
      - checkout
      - attach_workspace:
          at: ~/

  release:
    docker:
      - image: gebbissimo/ci_image:20221016-v1
    steps:
      - checkout
